apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Namespace.
  - ../../components/namespace/
  # Katib controller.
  - ../../components/controller/
  # Katib CRDs.
  - ../../components/crd/
  # Katib DB manager.
  - ../../components/db-manager/
  # Katib UI.
  - ../../components/ui/
  # Katib Cert Generator
  - ../../components/cert-generator/
  # Katib webhooks.
  - ../../components/webhook/
images:
  - name: docker.io/pkskubeflow/katib-controller:v0.9.0
    newName: docker.io/pkskubeflow/katib-controller
    newTag: v0.9.0
  - name: docker.io/pkskubeflow/katib-db-manager:v0.9.0
    newName: docker.io/pkskubeflow/katib-db-manager
    newTag: v0.9.0
  - name: docker.io/yuzhouge/katib-ui:latest
    newName: docker.io/yuzhouge/katib-ui
    newTag: latest
  - name: docker.io/kubeflowkatib/cert-generator
    newName: docker.io/kubeflowkatib/cert-generator
    newTag: v0.11.1
patchesStrategicMerge:
  - db-manager-patch.yaml
# Modify katib-mysql-secrets with parameters for the DB.
secretGenerator:
  - name: katib-mysql-secrets
    envs:
      - secrets.env
