apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: tensorboards-web-app
        image: yuzhouge/tensorboards-web-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: APP_SECURE_COOKIES
          value: "false"
        - name: APP_PREFIX
          value: $(TWA_PREFIX)
        - name: USERID_HEADER
          value: $(TWA_USERID_HEADER)
        - name: USERID_PREFIX
          value: $(TWA_USERID_PREFIX)
      serviceAccountName: service-account
