apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kfserving-controller-manager
  namespace: kfserving-system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: cestcai/kfserving-controller:v0.3.0
        name: manager
