apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../katib-cert-manager
  # Kubeflow Katib components.
  - kubeflow-katib-roles.yaml
  - ui-virtual-service.yaml
images:
  - name: docker.io/pkskubeflow/katib-controller:v0.9.0
    newName: docker.io/pkskubeflow/katib-controller
    newTag: v0.9.0
  - name: docker.io/pkskubeflow/katib-db-manager:v0.9.0
    newName: docker.io/pkskubeflow/katib-db-manager
    newTag: v0.9.0
  - name: docker.io/yuzhouge/katib-ui:latest
    newName: docker.io/yuzhouge/katib-ui
    newTag: latest

patchesStrategicMerge:
  - patches/remove-resources-patch.yaml

patchesJson6902:
  - path: patches/mysql-pvc.yaml
    target:
      version: v1
      name: katib-mysql
      kind: PersistentVolumeClaim
      namespace: kubeflow

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: KATIB_UI_NAMESPACE
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: katib-ui

configurations:
  - params.yaml
